### ISSUE TITLE
Waves not visible on light background

### ISSUE THREAD

**Issue by cenkingunlugu** [halildurmus/siri_wave#3]
When I put siri_wave like this:

```
  final controller = SiriWaveController(
      amplitude: .1,
      color: Color(0xff6695CF),
      frequency: 1,
      speed: .2
  );
```

```
SiriWave(
          controller: controller,
          style: SiriWaveStyle.ios_9,
          options: SiriWaveOptions(
            backgroundColor: Colors.transparent,
          ),
)
```

or like this:

```
SiriWave(
          controller: controller,
          style: SiriWaveStyle.ios_9,
          options: SiriWaveOptions(
            backgroundColor: Colors.white,
          ),
)
```

And also when my background is light-colored even if I set color of the controller on certain conditions like this:

```
final colors = [
  Color(0xff6695CF),
  Color(0xffA15DE6),
  Color(0xff141524),
];

```

In a stream or so if I do this:

```
controller.setAmplitude(1 + this.volume);
controller.setFrequency(5);
controller.setColor((colors..shuffle()).first);
```

I know that waves are there, but they are invisible.

If I change my SiriWaveOptions background color to a darker color or black color, waves become visible.

**Comment by halildurmus** [comment]
Thanks for reporting the issue. 

This should be fixed with #4 which makes `SiriWave`'s background transparent.

Also added support to show/hide the support bar on iOS 9 style waveform. If you are gonna use `SiriWave` on light backgrounds, you might wanna set `showSupportBar` to `false` to hide the bar since it looks a bit weird on light backgrounds.

Another thing I noticed in your code examples is that I think you are misusing the `color` property and `setColor` method of the `SiriWaveController` as it only works for iOS 7 style waveform. I may add support for changing the colors of the iOS 9 style waveform in the future.

**EDIT:** Just published a new version (`v0.3.0`).
